routes.py
from flask import render_template, redirect, url_for, Blueprint, flash
from datetime import date
from werkzeug.security import generate_password_hash, check_password_hash
from models import db, BlogPost, User, Comment
from forms import CreatePostForm, ContactForm, RegisterForm, LoginForm, CommentForm
from dotenv import load_dotenv
from email.mime.text import MIMEText
import smtplib, os, ssl
from flask_login import LoginManager, login_user, login_required, logout_user, current_user
from functools import wraps
from flask import abort


load_dotenv()
MY_EMAIL = os.getenv("MY_EMAIL")
MY_PASSWORD = os.getenv("MY_PASSWORD")
TO_EMAIL = os.getenv("TO_EMAIL")



routes = Blueprint('routes', __name__)
login_manager = LoginManager()

def send_email(to, subject, content):
    """Helper function to send emails"""
    context = ssl.create_default_context()
    msg = MIMEText(content, "plain", "utf-8")
    msg['Subject'] = subject
    msg['From'] = MY_EMAIL
    msg['To'] = to
    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465, context=context, timeout=20) as connection:
            connection.login(user=MY_EMAIL, password=MY_PASSWORD)
            connection.sendmail(
                from_addr=MY_EMAIL,
                to_addrs=to,
                msg=msg.as_string()
            )
        flash("Message sent successfully!", "success")
    except Exception as e:
        from main import app
        app.logger.error(f"Email failed: {str(e)}")
        flash("Failed to send message. Please try again later.", "danger")

def agent_only(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        #If id is not 1 then return abort with 403 error
        if not current_user.agent:
            return abort(403)
        #Otherwise continue with the route function
        return f(*args, **kwargs)
    return decorated_function

def admin_only(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        #If id is not 1 then return abort with 403 error
        if not current_user.admin:
            return abort(403)
        #Otherwise continue with the route function
        return f(*args, **kwargs)
    return decorated_function

@login_manager.user_loader
def load_user(user_id):
    return db.get_or_404(User, user_id)

@routes.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if not current_user.is_authenticated or not getattr(current_user, 'admin', False):
        del form.agent
        del form.admin
    if form.validate_on_submit():
        if User.query.filter_by(email=form.email.data).first():
            flash('Email already registered. Login instead.')
            return redirect(url_for('routes.login'))

        hashed_and_salted_password = generate_password_hash(
            form.password.data,
            method='pbkdf2:sha256',
            salt_length=8
        )

        agent = form.agent.data if 'agent' in form._fields else False
        admin = form.admin.data if 'admin' in form._fields else False

        new_user = User(
            name = form.name.data,
            email = form.email.data,
            phone = form.phone.data,
            password = hashed_and_salted_password,
            agent = agent,
            admin = admin
        )
        db.session.add(new_user)
        db.session.commit()
        login_user(new_user)
        return redirect(url_for('routes.get_all_posts'))

    return render_template("register.html", form=form)

@routes.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    email = form.email.data
    password = form.password.data
    if form.validate_on_submit():
        result = db.session.execute(db.select(User).where(User.email == email))
        user = result.scalar()
        if user:
            if check_password_hash(user.password, password):
                login_user(user)
                return redirect(url_for('routes.get_all_posts'))
            else:
                flash('Incorrect Password. Please try again', 'danger')
                return redirect(url_for('routes.login'))
        else:
            flash('User not found.', 'warning')
            return redirect(url_for('routes.login'))
    return render_template("login.html", form=form)

@routes.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('routes.get_all_posts'))

@routes.route('/')
def get_all_posts():
    result = db.session.execute(db.select(BlogPost).order_by(BlogPost.id.desc()))
    posts = result.scalars().all()
    return render_template("index.html", all_posts=posts)

@routes.route('/post/<int:post_id>', methods=['GET', 'POST'])
def show_post(post_id):
    from main import gravatar
    requested_post = db.get_or_404(BlogPost, post_id)
    comment_form = CommentForm()
    if comment_form.validate_on_submit():
        if current_user.is_authenticated:
            if not current_user.is_authenticated:
                flash("You need to login or register to comment.")
                return redirect(url_for("routes.login"))
        new_comment = Comment(
            comment_author=current_user,
            text=comment_form.comment_text.data,
            parent_post = requested_post,
            name = comment_form.name.data,
        )
        db.session.add(new_comment)
        db.session.commit()
        return redirect(url_for('routes.show_post', post_id=post_id))
    return render_template("post.html", post=requested_post,
                           form=comment_form, current_user=current_user)

@routes.route('/add_new_post', methods=['GET', 'POST'])
@login_required
@agent_only
def add_new_post():
    form = CreatePostForm()
    if form.validate_on_submit():
        if not current_user.agent:
            flash("You don't have permission to perform this action", "danger")
            return redirect(url_for('routes.get_all_posts'))
        new_post = BlogPost(
            title=form.title.data,
            subtitle=form.subtitle.data,
            date = date.today().strftime("%B %d, %Y"),
            body = form.body.data,
            img_url = form.img_url.data,
            author = current_user,
        )
        db.session.add(new_post)
        db.session.commit()
        return redirect(url_for('routes.get_all_posts'))
    return render_template("make-post.html", form=form)

@routes.route('/edit_post/<int:post_id>', methods=['GET', 'POST'])
@agent_only
@login_required
def edit_post(post_id):
    post = db.get_or_404(BlogPost, post_id)
    edit_form = CreatePostForm(
        title = post.title,
        subtitle = post.subtitle,
        body = post.body,
        img_url = post.img_url,
        author = post.author,
    )

    if edit_form.validate_on_submit():
        if not current_user.agent:
            flash("You don't have permission to perform this action", "danger")
            return redirect(url_for('routes.get_all_posts'))
        post.title = edit_form.title.data
        post.subtitle = edit_form.subtitle.data
        post.body = edit_form.body.data
        post.author = edit_form.author.data
        post.img_url = edit_form.img_url.data
        db.session.commit()
        return redirect(url_for('routes.show_post', post_id=post.id))
    return render_template('make-post.html', is_edit=True, form=edit_form)

@routes.route('/delete/<int:post_id>')
@admin_only
@login_required
def delete(post_id):
    post = db.get_or_404(BlogPost, post_id)
    if not current_user.admin:
        flash("You don't have permission to perform this action", "danger")
        return redirect(url_for('routes.get_all_posts'))
    db.session.delete(post)
    db.session.commit()
    return redirect(url_for('routes.get_all_posts', post_id=post_id))

@routes.route('/delete_comment/<int:comment_id>')
@admin_only
def delete_comment(comment_id):
    comment = db.get_or_404(Comment, comment_id)
    if not current_user.admin:
        flash("You don't have permission to perform this action", "danger")
        return redirect(url_for('routes.show_post', post_id=comment.post_id))
    db.session.delete(comment)
    db.session.commit()
    return redirect(url_for('routes.show_post', post_id=comment.post_id))

@routes.route("/about")
def about():
    return render_template("about.html")

@routes.route("/contact", methods=["GET", "POST"])
def contact():
    contact_form = ContactForm()
    if contact_form.validate_on_submit():
        content = (f'Name: {contact_form.name.data}\n'
                   f'Email: {contact_form.email.data}\n'
                   f'Phone Number: {contact_form.phone.data}\n'
                   f'Message: {contact_form.message.data}')
        send_email(to=TO_EMAIL,subject='Blog Contact Form', content=content)
        return redirect(url_for('routes.contact'))
    elif contact_form.is_submitted() and not contact_form.validate():
        flash("Please correct the errors in the form.", "danger")
    return render_template('contact.html', form=contact_form)

@routes.errorhandler(404)
def page_not_found(e):
    return render_template('404.html'), 404

@routes.errorhandler(500)
def internal_server_error(e):
    return render_template('500.html'), 500

@routes.context_processor
def inject_now():
    from datetime import datetime
    return {'year': datetime.now().year }

templates/about.html
{% include "header.html" %}

<!-- Page Header-->
<header
  class="masthead"
  style="background-image: url('../static/assets/img/about-bg.jpg')"
>
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="page-heading">
          <h1>About Me</h1>
          <span class="subheading">This is what I do.</span>
        </div>
      </div>
    </div>
  </div>
</header>
<!-- Main Content-->
<main class="mb-4">
  <div class="container px-4 px-lg-5">
    <div class="justify-content-left">
      <div class="col-12">
        <p>
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe
          nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis
          sit soluta odio, adipisci quas excepturi maxime quae totam ducimus
          consectetur?
        </p>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius
          praesentium recusandae illo eaque architecto error, repellendus iusto
          reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in
          officia voluptas voluptatibus, minus!
        </p>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut
          consequuntur magnam, excepturi aliquid ex itaque esse est vero natus
          quae optio aperiam soluta voluptatibus corporis atque iste neque sit
          tempora!
        </p>
      </div>
    </div>
  </div>
</main>

{% include "footer.html" %}

templates/contact.html
{% include "header.html" %}
{% from 'bootstrap/form.html' import render_form %}

<!-- Page Header-->
<header
  class="masthead"
  style="background-image: url('../static/assets/img/contact-bg.jpg')"
>
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="page-heading">
          {% if msg_sent: %}
          <h1>Successfully sent your message</h1>
          {% else: %}
          <h1>Contact Me</h1>
          {% endif %}
          <span class="subheading">Have questions? I have answers.</span>
        </div>
      </div>
    </div>
  </div>
</header>
<!-- Main Content-->
<main class="mb-4">
  <div class="container px-4 px-lg-5">
    <div class="">
      <div class="col-12">
        <p>
          Want to get in touch? Fill out the form below to send me a message and
          I will get back to you as soon as possible!
        </p>
        <div class="my-5">
        {{ render_form(form, button_map={"submit": "primary"}) }}
        </div>
      </div>
    </div>
  </div>
</main>

{% include "footer.html" %}

templates/footer.html
        <!-- Footer-->
        <footer class="border-top">
          <div class="container px-4 px-lg-5">
              <div class="row gx-4 gx-lg-5 justify-content-center">
                  <div class="col-md-10 col-lg-8 col-xl-7">
                      <ul class="list-inline text-center">
                          <li class="list-inline-item">
                              <a href="#!">
                                  <span class="fa-stack fa-lg">
                                      <i class="fas fa-circle fa-stack-2x"></i>
                                      <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                  </span>
                              </a>
                          </li>
                          <li class="list-inline-item">
                              <a href="#!">
                                  <span class="fa-stack fa-lg">
                                      <i class="fas fa-circle fa-stack-2x"></i>
                                      <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                  </span>
                              </a>
                          </li>
                          <li class="list-inline-item">
                              <a href="#!">
                                  <span class="fa-stack fa-lg">
                                      <i class="fas fa-circle fa-stack-2x"></i>
                                      <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                  </span>
                              </a>
                          </li>
                      </ul>
                      <div class="small text-center text-muted fst-italic">Copyright &copy; Mandel's Blog {{ year }}</div>
                  </div>
              </div>
          </div>
      </footer>
      <!-- Bootstrap core JS-->
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
      <!-- Core theme JS-->
      <script src="{{ url_for('static', filename='js/scripts.js') }}"></script>
  </body>
</html>

templates/header.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1288268350528103"
     crossorigin="anonymous"></script>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Mandel's Blog</title>
    {% block styles %}
    <!-- Load Bootstrap-Flask CSS here -->
    {{ bootstrap.load_css() }}
    <style>
      .form-group {
        margin-bottom: 1rem !important;
        }
    </style>
    <link
      rel="icon"
      type="image/x-icon"
      href="{{ url_for('static', filename='assets/favicon.ico') }}"
    />
    <!-- Font Awesome icons (free version)-->
    <script
      src="https://use.fontawesome.com/releases/v6.3.0/js/all.js"
      crossorigin="anonymous"
    ></script>
    <!-- Google fonts-->
    <link
      href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="{{ url_for('static', filename='css/styles.css') }}"
      rel="stylesheet"
    />
    {% endblock %}
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
      <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="/">Mandel's Blog</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarResponsive"
          aria-controls="navbarResponsive"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          Menu
          <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ms-auto py-4 py-lg-0">
            <li class="nav-item">
              <a
                class="nav-link px-lg-3 py-3 py-lg-4"
                href="{{ url_for('routes.get_all_posts') }}"
                >Home</a>
            </li>

            {% if not current_user.is_authenticated %}
            <li class="nav-item">
              <a
                class="nav-link px-lg-3 py-3 py-lg-4"
                href="{{ url_for('routes.login') }}"
                >Login</a>
            </li>
            {% endif %}
            {% if not current_user.is_authenticated or current_user.admin %}
            <li class="nav-item">
              <a
                class="nav-link px-lg-3 py-3 py-lg-4"
                href="{{ url_for('routes.register') }}"
                >Register</a>
            </li>
            {% endif %}
            {% if current_user.is_authenticated %}
            <li class="nav-item">
              <a
                class="nav-link px-lg-3 py-3 py-lg-4"
                href="{{ url_for('routes.logout') }}"
                >Log Out</a>
              {% endif %}
            </li>
            <li class="nav-item">
              <a
                class="nav-link px-lg-3 py-3 py-lg-4"
                href="{{ url_for('routes.about') }}"
                >About</a>
            </li>
            <li class="nav-item">
              <a
                class="nav-link px-lg-3 py-3 py-lg-4"
                href="{{ url_for('routes.contact') }}"
                >Contact</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    <div class="flashes">
      {% for category, message in messages %}
        <div class="alert alert-{{ category }} alert-dismissible fade show">
          {{ message }}
          <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        </div>
      {% endfor %}
    </div>
  {% endif %}
{% endwith %}
  </body>
</html>

templates/index.html
{% include "header.html" %}

<!-- Page Header-->
<header
  class="masthead"
  style="background-image: url('../static/assets/img/home-bg.jpg')"
>
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="site-heading">
          <h1>Mandel's Blog</h1>
          <span class="subheading">A Blog of Excellence</span>
        </div>
      </div>
    </div>
  </div>
</header>
<!-- Main Content-->
<div class="container position-relative px-4 px-lg-5">
  <div class="row gx-4 gx-lg-5 justify-content-left">
    <div class="col-12 text-start">
      <!-- Post preview-->
      {% for post in all_posts %}
      <div class="post-preview">
        <a href="{{ url_for('routes.show_post', post_id=post.id) }}">
          <h2 class="post-title">{{ post.title }}</h2>
          <h3 class="post-subtitle">{{ post.subtitle }}</h3>
        </a>
        <p class="post-meta">
          Posted by
          <a href="#">{{post.author.name.title() }}</a>
          on {{post.date}}
          {% if current_user.admin %}
          <a href="{{ url_for('routes.delete', post_id=post.id) }}">✘</a>
          {% endif %}
        </p>
      </div>
      <!-- Divider-->
      <hr class="my-4" />
      {% endfor %}

      <!-- New Post -->
      {% if current_user.agent %}
      <div class="d-flex justify-content-end mb-4">
        <a class="btn btn-secondary text-uppercase me-3" href="#!">Older Posts →</a>
        <a
          class="btn btn-primary float-right"
          href="{{ url_for('routes.add_new_post') }}"
          >Create New Post</a>
      </div>
      {% endif %}
      <!-- Pager-->
      <div class="d-flex justify-content-end mb-4">

      </div>
    </div>
  </div>
</div>

{% include "footer.html" %}

templates/login.html
{% from "bootstrap5/form.html" import render_form %}
{% block content %} {%include "header.html" %}

<!-- Page Header -->
<header
  class="masthead"
  style="background-image: url('../static/assets/img/login-bg.jpg')"
>
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="page-heading">
          <h1>Log In</h1>
          <span class="subheading">Welcome Back!</span>
        </div>
      </div>
    </div>
  </div>
</header>

<main class="mb-4">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        {{ render_form(form) }}
      </div>
    </div>
  </div>
</main>

{% include "footer.html" %} {% endblock %}

templates/make-post.html
{% block content %} {% include "header.html" %}
{% from 'bootstrap/form.html' import render_form %}
<!-- Page Header -->
<header
  class="masthead"
  style="background-image: url('../static/assets/img/edit-bg.jpg')"
>
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="page-heading">

          {% if is_edit: %}
          <h1>Edit Post</h1>
          {% else: %}
          <h1>New Post</h1>
          {% endif %}
          <span class="subheading"
            >You're going to make a great blog post!</span
          >
        </div>
      </div>
    </div>
  </div>
</header>

<main class="mb-4">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        {{ ckeditor.load() }}
        {{ ckeditor.config(name='body') }}
        {{ render_form(form, novalidate=True, button_map={"submit": "primary"}) }}
      </div>
    </div>
  </div>
</main>
{% include "footer.html" %} {% endblock %}

templates/post.html
{% include "header.html" %}
{% from "bootstrap5/form.html" import render_form %}

<!-- Page Header-->
<header class="masthead" style="background-image: url('{{post.img_url}}')">
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-12">
        <div class="post-heading text-center">
          <h1 class="w-100 mb-3">{{ post.title }}</h1>
          <h2 class="subheading w-100 mb-4">{{ post.subtitle }}</h2>
          <div class="meta w-100">
          <span class="posted-by">Posted by {{ post.author.name.title() }} on {{ post.date }}</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>

<!-- Post Content -->
<article>
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-12">
      <div class="text-start">
        {{ post.body|safe }}
        {% if current_user.agent %}
        <div class="d-flex justify-content-end mb-4">
          <a
            class="btn btn-primary float-right"
            href="{{ url_for('routes.edit_post', post_id=post.id) }}"
            >Edit Post</a>
        </div>
        {% endif %}

                <!-- Comments Area -->
        <div class="comments-section mt-5">
        {{ render_form(form, novalidate=True, button_map={"submit": "primary"}) }}
        <p></p>
        <div class="comment">
          <ul class="commentList">
            {% for comment in post.comments: %}
            <li>
              <div class="commenterImage">
                <img  src="{{ comment.comment_author.name | gravatar }}" style="width:50px;height:50px;" />
              </div>
              <div class="commentText">
                <p>{{comment.text|safe}}
                  {% if current_user.admin %}
                  <a href="{{ url_for('routes.delete_comment', comment_id=comment.id) }}">✘</a>
                  {% endif %}
                </p>
                <span class="date sub-text">{{comment.comment_author.name.title() }}</span>
              </div>
            </li>
             {% endfor %}
          </ul>
        </div>
        </div>
      </div>
      </div>
    </div>
  </div>
</article>

{% include "footer.html" %}

templates/register.html
{% block content %} {% include "header.html" %}
{% from "bootstrap5/form.html" import render_form %}

<!-- Page Header -->
<header
  class="masthead"
  style="background-image: url('../static/assets/img/register-bg.jpg')"
>
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="page-heading">
          <h1>Register</h1>
          <span class="subheading">Start Contributing to the Blog!</span>
        </div>
      </div>
    </div>
  </div>
</header>

<main class="mb-4">
  <div class="container px-4 px-lg-5">
    <div class="">
      <div class="col-12 text-start">
        {{ render_form(form, button_map={"submit": "primary"}) }}
      </div>
    </div>
  </div>
</main>

{% include "footer.html" %}
{% endblock %}